### ISSUE TITLE
mtcnn/saved_model.pb

### ISSUE THREAD

**Issue by dota2015** [huangh12/py_face_recognition#1]
Hi:
How to train mtcnn/saved_model.pb ?
I use the model https://github.com/imistyrain/MTCNN/blob/master/tensorflow/mtcnn.pb, it doesn't work.

Can you tell me how to train the model or how to transform it?

**Comment by huangh12** [comment]
Hi @dota2015, this repo has contained a [transformed mtcnn model](https://github.com/huangh12/py_face_recognition/tree/master/models/mtcnn), you can directly use it. The mtcnn model is converted from its caffe version inspired by [this project](https://github.com/blaueck/tf-mtcnn).

**Comment by dota2015** [comment]
OK.Thks!
I use [transformed mtcnn model](https://github.com/huangh12/py_face_recognition/tree/master/models/mtcnn), but in my video scene, there will be some false positives. [It's like this.](https://sm.ms/image/ci4WIHFgPTZV3h5)  So I think I should train the mtcnn model.  
Do you have any good suggestions?

**Comment by huangh12** [comment]
Of course, you can train the mtcnn if you have plenty of annotated data in your video scene.  But at the first, I will suggest you to tune the score thresh of current mtcnn model and use some postprocessing strategy, (e.g., using box area prior) to reduce false postive. 
Good luck!

**Comment by dota2015** [comment]
> Of course, you can train the mtcnn if you have plenty of annotated data in your video scene. But at the first, I will suggest you to tune the score thresh of current mtcnn model and use some postprocessing strategy, (e.g., using box area prior) to reduce false postive. Good luck!

Thank you~!
